### ISSUE TITLE
Not compatible with dio 3.0.10

### ISSUE THREAD

**Issue by WangZhuo2015** [leancloud/Storage-SDK-Flutter#81]
leancloud_storage: ^0.4.2 + Dio 3.0.10 throw the error below when calling any network-related API.
After manually replace Dio 3.0.10 with 3.0.09 in pubspec.lock this error disappeared.

```shell
Syncing files to device iPhone 11 Pro Max...
Restarted application in 537ms.
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: type '_ContentType' is not a subtype of type 'String'
#0      _HttpHeaders._addContentType (dart:_http/http_headers.dart:461:41)
#1      _HttpHeaders._add (dart:_http/http_headers.dart:351:11)
#2      _HttpHeaders._addAll (dart:_http/http_headers.dart:74:7)
#3      _HttpHeaders.set (dart:_http/http_headers.dart:92:5)
#4      DefaultHttpClientAdapter.fetch.<anonymous closure> (package:dio/src/adapters/io_adapter.dart:49:57)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#6      DefaultHttpClientAdapter.fetch (package:dio/src/adapters/io_adapter.dart:49:23)
<asynchronous suspension>
#7      DioMixin._dispatchRequest (package:dio/src/dio.dart:922:46)
<asynchronous suspension>
#8      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
#9      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1121:2<…>

```

**Comment by onerain88** [comment]
Due of Dio changed the api of ContentType, but not comply the rule of version.
So I fixed the Dio version to 3.0.8 in [0.4.3](https://pub.dev/packages/leancloud_storage).
